const prefix = '/api/commerce1'
const ws = {
    wsingresoproducto: prefix + '/ingresoproducto',
    wssalidaproducto: prefix + '/salidaproducto',
    wsmoneda: prefix + '/moneda',
    wssearchproducto: prefix + '/producto/search',
    wstiposalingresotrans: prefix + '/ingrsaltratipo',
    wsalmacen: prefix + '/almacen',
    wsgetalmacenprod: prefix + '/producto/almacenprod',
    wscompra: prefix + '/compra',
    wssucursal: prefix + '/sucursal',
    wssearchproveedorcod: prefix + '/proveedor/searchcod',
    wssearchproveedornom: prefix + '/proveedor/searchnombre',
    wssearchproductoid: prefix + '/producto/searchid',
    wssearchproductodesc: prefix + '/producto/searchdesc',
    wsunidadmedida: prefix + '/unidadmedida',
    //wsshowproveedor: '/commerce/admin/showProveedor',
    wsshowproveedor: prefix + '/proveedor/show',
    wsproducto: prefix + '/producto',
    wslistaprecio: prefix + '/listaprecio',
    wsallproductos: prefix + '/productosall',
    wslistaproductoslp: prefix + '/listaproductos',
    wsvendedor: prefix + '/vendedor',
    wssearchventaidcod : prefix + '/venta/searchidcod',
    wssearchcompraidcod : prefix + '/compra/searchidcod',
    wscobranza: prefix + '/cobro',
    wsgetcuotasventa: prefix + '/venta/getcuotas',
    wsgetcuotascompra: prefix + '/compra/getcuotas',
    wspagos: prefix + '/pago',
    wsventa: prefix + '/venta',
    wsproforma: prefix + '/proforma',
    wssearchclienteidcod: prefix + '/cliente/searchidcod',
    wssearchclientenombre: prefix + '/cliente/searchnombre',
    wssearchvehiculoidcod: prefix + '/vehiculo/searchidcod',
    wssearchvehiculoplaca: prefix + '/vehiculo/searchplaca',
    wssearchvendedoridcod: prefix + '/vendedor/searchidcod',
    wssearchvendedornombre: prefix + '/vendedor/searchnombre',
    wssearchvendedorfullname: prefix + '/vendedor/searchfullname',
    wsverificarstock: prefix + '/verifistock',
    wsgetprecioprod: prefix + '/getPrecio',
    wsinventariocorte: prefix + '/inventariocorte',
    wsgetvehiculo: '/commerce/admin/getVehiculo?id=',
    wssearchlistaprecio: prefix + '/listaprecio/search',
    wslistaprecios: prefix + '/listaprecios',
    wsproductos: prefix + '/productos',
    wsclientes: prefix + '/clientes',
    wsvendedores: prefix + '/vendedores',
    wssearchprodidalm: prefix + '/producto/searchidalmacen',
    wssearchproddescalm: prefix + '/producto/searchdescalmacen',
    wsalmacenproductos: prefix + '/almacen/productos',
    wsindexproveedor: '/commerce/admin/indexProveedor',
    wsgetnroventa: prefix + '/nroventa',
    wsgetnroproforma: prefix + '/nroproforma',
    wsgetnrohistorico: prefix + '/nrohistorico',
    wsgethistorialvehiculo: prefix + '/gethistorialvehiculo',
    wsgetpartesvehiculo: prefix + '/getpartesvehiculo',
    wsproductosall: prefix + '/getallproductos',
    wsproductosalmacenes: prefix + '/getproductosalmacenes',
    wsfamilia: prefix + '/familia',
    wsproductosxfamilia: prefix + '/getproductosfamilia',
    wsprodalmacenes: prefix + '/prodalmacenes',
    wssearchprodbytipo: prefix + '/producto/searchproducto',
    wssearchinventarioidcod: prefix + '/inventariocorte/searchidcod',
    wssearchonlyproduct: prefix + '/onlyproducto/search',
    wsgetpartesvehiculoall: '/commerce/admin/getParteVehiculo',
    wsalmacenubicacion: prefix + '/almacenubi',
    wspcaracteristica: prefix + '/pcaracteristica',
    wscliente: prefix + '/cliente',
    wstipocontacredito: prefix + '/tipocontacredito',
    wstraercomisionvend: prefix + '/traercomisionvendedor',
    wstraerunidadmed: prefix + '/traerunidad',
    wsshowcliente: prefix + '/showCliente',
    wscomisionventa: prefix + '/comisionventa',
    wsreferenciascont: prefix + '/referenciacontacto',
    wspermisions: prefix + '/usuario/permisions',
    wslogin: prefix + '/login',
    wslogout: prefix + '/usuario/logout',
    wsgetlistasactivas: prefix + '/obtenerlistas',
    wsindexfamilia: prefix + '/indexFamilia',

    wsconfigfabrica: '/config/configfabrica',
    wsconfigcliente: prefix + '/config/configcliente',
    wsverificarsesion: prefix + '/verifsesion',
    apiCaptcha: 'https://www.google.com/recaptcha/api/siteverify',

    wsListCharacteristics: prefix + '/listacaracteristica',
    wsBuscarCaracteristica: prefix + '/buscarcaracteristica',
    wsPaginacionVehiculoCaracteristica: prefix + '/paginacion-vehiculo-caracteristica',
    wsBusquedaCliente: prefix + '/busquedacliente',
    wsTipoClientes: prefix + '/tipocliente',
    wsBusquedaTipoCliente: prefix + '/busqueda_tipo_cliente',
    wsCantidadPaginacionTipoCliente: prefix + '/cantidad_paginacion_tipo_cliente',
    wsGetTipoClientes: prefix + '/get_tipo_clientes',

    wsGetUnidadesMedida: prefix + '/get_unidades_medida',
    wsGetUnidadMedidaBusqueda: prefix + '/get_unidad_medida_busqueda',
    wsGetUnidadesMedidaPaginacion: prefix + '/get_unidad_medida_paginacion',

    wsGetTipoMonedas: prefix + '/get_tipo_monedas',
    wsGetTipoMonedaBusqueda: prefix + '/get_tipo_moneda_busqueda',
    wsGetTipoMonedasPaginacion: prefix + '/get_tipo_monedas_paginacion',

    wsGetTipoTraspasos: prefix + '/get_tipo_traspasos',
    wsGetTipoTraspaso: prefix + '/get_tipo_traspaso_busqueda',
    wsGetTipoTraspasosPaginacion: prefix + '/get_tipo_traspasos_paginacion',

    wsGetSucursales: prefix + '/get_sucursales',
    wsGetSucursalBusqueda: prefix + '/get_sucursal_busqueda',
    wsGetSucursalesPaginacion: prefix + '/get_sucursales_paginacion',

    wsGetAlmacenes: prefix + '/get_almacenes',
    wsGetAlmacenBusqueda: prefix + '/get_almacen_busqueda',
    wsGetAlmacenesPaginacion: prefix + '/get_almacenes_paginacion',

    wsGetTipoVehiculos: prefix + '/get_tipo_vehiculos',
    wsGetCiudades: prefix + '/get_ciudades',
    wsGetUbicacionAlmacenes: prefix + '/get_ubicacion_almacenes',
    wsGetUbicaciones: prefix + '/get_ubicaciones',

    wsGetVehiculos: prefix + '/get_vehiculos',
    wsGetVehiculoBusqueda: prefix + '/get_vehiculo_busqueda',
    wsGetVehiculosPaginacion: prefix + '/get_vehiculos_paginacion',

    wsGetHistoriaVehiculos: prefix + '/get_historia_vehiculos',
    wsGetHistoriaVehiculosBusqueda: prefix + '/get_historia_vehiculos_busqueda',
    wsGetHistoriaVehiculosPaginacion: prefix + '/get_historia_vehiculos_paginacion',

    wsPartesVehiculos: prefix + '/partes_vehiculos',
    wsGetVehiculoPartes: prefix + '/get_vehiculo_partes',
    wsGetVehiculoParteBusqueda: prefix + '/get_vehiculo_partes_busqueda',
    wsGetVehiculoPartePaginacion: prefix + '/get_vehiculo_partes_paginacion',

    wstipovehiculo: prefix + '/tipovehiculo',
    wsclivehiculosidcod: prefix + '/cliente/searchvehiculoidcod',
    wsclivehiculosplaca: prefix + '/cliente/searchvehiculoplaca',
    wsCambiarPaginacion: prefix + '/cambiarpaginacion',
    wscodvehiculovalido: prefix + '/vehiculo/codigovalido',
    wscodproductovalido: prefix + '/producto/validarcodigo',
    wscodingresoprodvalido: prefix + '/ingresoprod/validarcodigo',
    wscodsalidaprodvalido: prefix + '/salidaprod/validarcodigo',
    wscodclientevalido: prefix + '/cliente/validarcodigo',
    wscodvendedorvalido: prefix + '/vendedor/validarcodigo',
    wscodventavalido: prefix + '/venta/validarcodigo',
    wscodproformavalido: prefix + '/proforma/validarcodigo',
    wscodcobrovalido: prefix + '/cobranza/validarcodigo',
    wscodproveedorvalido: prefix + '/proveedor/validarcodigo',
    wscodcompravalido: prefix + '/compra/validarcodigo',
    wscodpagovalido: prefix + '/pago/validarcodigo',
    wssearchusuarioid: prefix + '/usuario/searchid',
    wssearchusuarionom: prefix + '/usuario/searchnom',
    wsusuariosconectados: prefix + '/usuario/conectados',
    wssearchcliventas: prefix + '/clienteventas/search',
    wsgetventasclientes: prefix + '/clientes/getVentasCliente',
    wssearchprovecompras: prefix + '/provcompras/search',
    wsgetcomprasproveedor: prefix + '/proveedores/getCompras',
    wssearchcliproformas: prefix + '/clienteproformas/search',
    wsgetproformascliente: prefix + '/clientes/getProformasCliente',
    wsproformacompleta: prefix + '/proformacompleta',
    wscreateventa: prefix + '/venta/create',
    wsProveedores: prefix + '/proveedores',
    wsGetCompras: prefix + '/getCompras',

    wscreateproforma: prefix + '/proforma/create',
    wscreatecompra: prefix + '/compra/create',

    wsusuario: prefix + '/usuario',
    wsusuario_delete: prefix + '/usuario/delete',
    wsusuario_store: prefix + '/usuario/post',
};

export default ws;
